// <auto-generated />
using System;
using HerkesYazarOlsun.DataLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HerkesYazarOlsun.DataLayer.Migrations
{
    [DbContext(typeof(HerkesyazarolsunContext))]
    [Migration("20230424194046_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.KISILER", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("AD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SOYAD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("KISILER");
                });
#pragma warning restore 612, 618
        }
    }
}
