// <auto-generated />
using System;
using HerkesYazarOlsun.DataLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HerkesYazarOlsun.DataLayer.Migrations
{
    [DbContext(typeof(HerkesYazaOlsunContext))]
    [Migration("20231011153107_addedFavoiler")]
    partial class addedFavoiler
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Books", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("ARKAKAPAKFOTO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ARKAKAPAKYAZISI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CategoriId")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ONKAPAKFOTO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ONSOZ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TAMAMLANDIMI")
                        .HasColumnType("boolean");

                    b.Property<long>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<bool>("YAYINDAMI")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.BooksPages", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long>("BooksId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PageFoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PageWrite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("BooksPages");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Category", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<int>("BooksId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.FAVORILER", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("BOOKS_ID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_ID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("FAVORILER");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Users", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PASSWORD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SURNAME")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TCKNO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
