// <auto-generated />
using System;
using HerkesYazarOlsun.DataLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HerkesYazarOlsun.DataLayer.Migrations
{
    [DbContext(typeof(HerkesYazaOlsunContext))]
    [Migration("20231217125446_addedkolonisFollow")]
    partial class addedkolonisFollow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Books", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("ARKAKAPAKFOTO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ARKAKAPAKYAZISI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CategoriId")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ONKAPAKFOTO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ONSOZ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TAMAMLANDIMI")
                        .HasColumnType("boolean");

                    b.Property<long>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<bool>("YAYINDAMI")
                        .HasColumnType("boolean");

                    b.Property<long>("YazarId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.BooksPages", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long>("BooksId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PageFoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PageWrite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("BooksPages");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.BooksStars", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<int>("BookaId")
                        .HasColumnType("integer");

                    b.Property<int>("LoginUserId")
                        .HasColumnType("integer");

                    b.Property<int>("StarPuani")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("BooksStars");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Category", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<int>("BooksId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.FAVORILER", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long>("BOOKS_ID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("FAVORILER");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.FAVORI_YAZARLAR", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<int>("LoginUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<int>("YazarId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("FAVORI_YAZARLAR");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.FavoriBooks", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long>("BOOKS_ID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("FavoriBooks");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Users", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EMAIL")
                        .HasColumnType("text");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NAME")
                        .HasColumnType("text");

                    b.Property<string>("PASSWORD")
                        .HasColumnType("text");

                    b.Property<string>("SURNAME")
                        .HasColumnType("text");

                    b.Property<string>("TELNO")
                        .HasColumnType("text");

                    b.Property<string>("USERNAME")
                        .HasColumnType("text");

                    b.Property<long>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<int>("isEmail")
                        .HasColumnType("integer");

                    b.Property<int>("isTelno")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.WriterFollow", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<int>("LoginUserId")
                        .HasColumnType("integer");

                    b.Property<int>("YazarId")
                        .HasColumnType("integer");

                    b.Property<int>("isFollow")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("WriterFollow");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.WriterStars", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<int>("LoginUserId")
                        .HasColumnType("integer");

                    b.Property<int>("StarPuani")
                        .HasColumnType("integer");

                    b.Property<int>("YazarId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("WriterStars");
                });
#pragma warning restore 612, 618
        }
    }
}
