// <auto-generated />
using System;
using HerkesYazarOlsun.DataLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HerkesYazarOlsun.DataLayer.Migrations
{
    [DbContext(typeof(HerkesYazaOlsunContext))]
    [Migration("20250216153033_AddCarouselDuyuruAddNewBaseEntity")]
    partial class AddCarouselDuyuruAddNewBaseEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.AccountLogin", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<bool?>("AllowRefresh")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsPersistent")
                        .HasColumnType("boolean");

                    b.Property<long>("LoginUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("text");

                    b.Property<bool>("RememberLogin")
                        .HasColumnType("boolean");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("text");

                    b.Property<string>("benihatirla")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("sifre")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("AccountLogin");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Ayarlar", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long>("BildirimID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<long>("LoginUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("text");

                    b.Property<long>("ProfileID")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("text");

                    b.Property<long>("UserDetailID")
                        .HasColumnType("bigint");

                    b.Property<int?>("isDegisiklik")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Ayarlar");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Bildirimler", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsKitapYayin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsKitapYorum")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTakip")
                        .HasColumnType("boolean");

                    b.Property<long?>("LoginUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("text");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Bildirimler");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Books", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("ARKAKAPAKFOTO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ARKAKAPAKYAZISI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CategoriId")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("text");

                    b.Property<string>("ONKAPAKFOTO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ONSOZ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TAMAMLANDIMI")
                        .HasColumnType("boolean");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("text");

                    b.Property<bool>("YAYINDAMI")
                        .HasColumnType("boolean");

                    b.Property<long>("YazarId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.BooksComment", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("BookId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<long>("LoginUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("text");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("BooksComment");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.BooksDegerlendirme", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("BookId")
                        .HasColumnType("bigint");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KONU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("LoginUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StarPuani")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("BooksDegerlendirme");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.BooksPages", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long>("BooksId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("text");

                    b.Property<string>("PageFoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PageWrite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PageWriteBase64")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("BooksPages");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.BooksStars", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<int>("BookaId")
                        .HasColumnType("integer");

                    b.Property<int>("LoginUserId")
                        .HasColumnType("integer");

                    b.Property<int>("StarPuani")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("BooksStars");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.CarouselDuyuru", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ICERIK")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ICERIK_TARIHI")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ICON")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("text");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("CarouselDuyuru");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Category", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<int>("BooksId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.FAVORILER", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long>("BOOKS_ID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("text");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("FAVORILER");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.FAVORI_YAZARLAR", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<int>("LoginUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("text");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("text");

                    b.Property<int>("YazarId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("FAVORI_YAZARLAR");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.FavoriBooks", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<long>("BOOKS_ID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("text");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("FavoriBooks");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Kartlar", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Cvv")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<string>("KartNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KartTarihi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KartTarihiAy")
                        .HasColumnType("integer");

                    b.Property<int>("KartTarihiYil")
                        .HasColumnType("integer");

                    b.Property<string>("KartUzerindekiIsim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("text");

                    b.Property<long>("OdemeId")
                        .HasColumnType("bigint");

                    b.Property<long>("Tutar")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Kartlar");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Odeme", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<long>("KitapId")
                        .HasColumnType("bigint");

                    b.Property<long>("LoginUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("text");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("text");

                    b.Property<bool>("isOdeme")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.ToTable("Odeme");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.OdemeSponsorlari", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<long>("KitapId")
                        .HasColumnType("bigint");

                    b.Property<long>("LoginUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mesaj")
                        .HasColumnType("text");

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("text");

                    b.Property<long>("SponsorId")
                        .HasColumnType("bigint");

                    b.Property<long>("Tel")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("OdemeSponsorlari");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Profil", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<long?>("LoginUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MimeType")
                        .HasColumnType("text");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("text");

                    b.Property<string>("ProfilArkaplanRenkKodu")
                        .HasColumnType("text");

                    b.Property<string>("ProfilArkaplanResmi")
                        .HasColumnType("text");

                    b.Property<string>("ProfilResimBase64")
                        .HasColumnType("text");

                    b.Property<string>("ProfilResimName")
                        .HasColumnType("text");

                    b.Property<string>("ProfilResimURl")
                        .HasColumnType("text");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Profil");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Sponsorlar", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("ICON")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SponsorAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Sponsorlar");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Users", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EMAIL")
                        .HasColumnType("text");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NAME")
                        .HasColumnType("text");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("text");

                    b.Property<string>("PASSWORD")
                        .HasColumnType("text");

                    b.Property<string>("SURNAME")
                        .HasColumnType("text");

                    b.Property<string>("TELNO")
                        .HasColumnType("text");

                    b.Property<string>("USERNAME")
                        .HasColumnType("text");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("text");

                    b.Property<int>("isEmail")
                        .HasColumnType("integer");

                    b.Property<int>("isTelno")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.UsersDetails", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FacebookLink")
                        .HasColumnType("text");

                    b.Property<string>("HAKKINDA")
                        .HasColumnType("text");

                    b.Property<long>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<string>("InstagramLink")
                        .HasColumnType("text");

                    b.Property<string>("LinkedinLink")
                        .HasColumnType("text");

                    b.Property<long?>("LoginUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("text");

                    b.Property<long?>("TEL")
                        .HasColumnType("bigint");

                    b.Property<string>("TwitterLink")
                        .HasColumnType("text");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("text");

                    b.Property<string>("WebSite")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("UsersDetails");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.WriterFollow", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<int>("LoginUserId")
                        .HasColumnType("integer");

                    b.Property<int>("YazarId")
                        .HasColumnType("integer");

                    b.Property<int>("isFollow")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("WriterFollow");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.WriterStars", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<int>("LoginUserId")
                        .HasColumnType("integer");

                    b.Property<int>("StarPuani")
                        .HasColumnType("integer");

                    b.Property<int>("YazarId")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("WriterStars");
                });
#pragma warning restore 612, 618
        }
    }
}
