// <auto-generated />
using System;
using HerkesYazarOlsun.DataLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HerkesYazarOlsun.DataLayer.SqlServerMigrations
{
    [DbContext(typeof(SqlServerContext))]
    [Migration("20251026173808_categortconfig2")]
    partial class categortconfig2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.AccountLogin", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<bool?>("AllowRefresh")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long?>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsPersistent")
                        .HasColumnType("bit");

                    b.Property<long>("LoginUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RememberLogin")
                        .HasColumnType("bit");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("benihatirla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sifre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("AccountLogin");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Ayarlar", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("BildirimID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long?>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<long>("LoginUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProfileID")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserDetailID")
                        .HasColumnType("bigint");

                    b.Property<int?>("isDegisiklik")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Ayarlar");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Bildirimler", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long?>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsKitapYayin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsKitapYorum")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTakip")
                        .HasColumnType("bit");

                    b.Property<long?>("LoginUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Bildirimler");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Books", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("ARKAKAPAKFOTO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARKAKAPAKFOTOPATH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARKAKAPAKYAZISI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BooksStarsId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CategoriId")
                        .HasColumnType("int");

                    b.Property<int?>("FavoriBooksId")
                        .HasColumnType("int");

                    b.Property<long?>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long?>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ONKAPAKFOTO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ONKAPAKFOTOPATH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ONSOZ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TAMAMLANDIMI")
                        .HasColumnType("bit");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("YAYINDAMI")
                        .HasColumnType("bit");

                    b.Property<int?>("YayinAyarId")
                        .HasColumnType("int");

                    b.Property<long?>("YazarId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("CategoriId");

                    b.HasIndex("YazarId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.BooksComment", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("BookId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long?>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<long>("LoginUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StarPuani")
                        .HasColumnType("int");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BookId");

                    b.ToTable("BooksComment");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.BooksDegerlendirme", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("ACIKLAMA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("BookId")
                        .HasColumnType("bigint");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KONU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LoginUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StarPuani")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BookId");

                    b.ToTable("BooksDegerlendirme");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.BooksPages", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("BookId")
                        .HasColumnType("bigint");

                    b.Property<long?>("BooksID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long?>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageFoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageWrite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageWriteBase64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BookId");

                    b.HasIndex("BooksID");

                    b.ToTable("BooksPages");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.BooksStars", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long?>("BookId")
                        .HasColumnType("bigint");

                    b.Property<int>("LoginUserId")
                        .HasColumnType("int");

                    b.Property<int>("StarPuani")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BookId");

                    b.ToTable("BooksStars");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.CarouselDuyuru", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("ICERIK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ICERIK_TARIHI")
                        .HasColumnType("datetime2");

                    b.Property<string>("ICON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long?>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RENK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CarouselDuyuru");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.CategoryYayinAyarlari", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("ToplamBegeni")
                        .HasColumnType("int");

                    b.Property<int?>("ToplamDegerlendirme")
                        .HasColumnType("int");

                    b.Property<int?>("ToplamYildiz")
                        .HasColumnType("int");

                    b.Property<int?>("ToplamYorum")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId")
                        .IsUnique()
                        .HasFilter("[CategoryId] IS NOT NULL");

                    b.ToTable("CategoryYayinAyarlari");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.FavoriBooks", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long?>("BookId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long?>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("FavoriBooks");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.FavoriYazarlar", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long?>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<int>("LoginUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YazarId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("FavoriYazarlar");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Favoriler", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("BOOKS_ID")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long?>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("USER_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Favoriler");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Kartlar", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<long>("Cvv")
                        .HasColumnType("bigint");

                    b.Property<long?>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long?>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<string>("KartNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KartTarihi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KartTarihiAy")
                        .HasColumnType("int");

                    b.Property<int>("KartTarihiYil")
                        .HasColumnType("int");

                    b.Property<string>("KartUzerindekiIsim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OdemeId")
                        .HasColumnType("bigint");

                    b.Property<long>("Tutar")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Kartlar");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Odeme", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long?>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<long>("KitapId")
                        .HasColumnType("bigint");

                    b.Property<long>("LoginUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isOdeme")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Odeme");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.OdemeSponsorlari", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long?>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<long>("KitapId")
                        .HasColumnType("bigint");

                    b.Property<long>("LoginUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mesaj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SponsorId")
                        .HasColumnType("bigint");

                    b.Property<long>("Tel")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("OdemeSponsorlari");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Profil", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<long?>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long?>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("MimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilArkaplanRenkKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilArkaplanResmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilResimBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilResimName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilResimURl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Profil");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Sponsorlar", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("ICON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long?>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SponsorAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Sponsorlar");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Talepler", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("ADISOYADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long?>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<string>("KONU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KONU_ID")
                        .HasColumnType("int");

                    b.Property<string>("MESAJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TARIHI")
                        .HasColumnType("datetime2");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Talepler");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Users", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long?>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PASSWORD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SURNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TELNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USERNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("isEmail")
                        .HasColumnType("int");

                    b.Property<int?>("isSozlesmeOnay")
                        .HasColumnType("int");

                    b.Property<int>("isTelno")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.UsersDetails", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("CREATE_AT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacebookLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HAKKINDA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("IS_DELETED")
                        .HasColumnType("bigint");

                    b.Property<long?>("IS_MODIFIED")
                        .HasColumnType("bigint");

                    b.Property<string>("InstagramLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedinLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("LoginUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("MODIFIED_AT")
                        .HasColumnType("datetime2");

                    b.Property<string>("OLUSTURAN_EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TEL")
                        .HasColumnType("bigint");

                    b.Property<string>("TwitterLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("USER_CREATED_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("USER_MODIFIED_ID")
                        .HasColumnType("bigint");

                    b.Property<string>("USER_MODIFIED_MAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebSite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("LoginUserId");

                    b.ToTable("UsersDetails");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.WriterFollow", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long?>("LoginUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("YazarId")
                        .HasColumnType("bigint");

                    b.Property<int>("isFollow")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LoginUserId");

                    b.HasIndex("YazarId");

                    b.ToTable("WriterFollow");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.WriterStars", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long?>("LoginUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("StarPuani")
                        .HasColumnType("int");

                    b.Property<long?>("YazarId")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("LoginUserId");

                    b.HasIndex("YazarId");

                    b.ToTable("WriterStars");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.YayinAyarlari", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<long?>("BookId")
                        .HasColumnType("bigint");

                    b.Property<int?>("ToplamBegeni")
                        .HasColumnType("int");

                    b.Property<int?>("ToplamDegerlendirme")
                        .HasColumnType("int");

                    b.Property<int?>("ToplamYildiz")
                        .HasColumnType("int");

                    b.Property<int?>("ToplamYorum")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BookId")
                        .IsUnique()
                        .HasFilter("[BookId] IS NOT NULL");

                    b.ToTable("YayinAyarlari");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Books", b =>
                {
                    b.HasOne("HerkesYazarOlsun.Model.Entity.Category", "Categori")
                        .WithMany()
                        .HasForeignKey("CategoriId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HerkesYazarOlsun.Model.Entity.Users", "Yazar")
                        .WithMany()
                        .HasForeignKey("YazarId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Categori");

                    b.Navigation("Yazar");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.BooksComment", b =>
                {
                    b.HasOne("HerkesYazarOlsun.Model.Entity.Books", "Book")
                        .WithMany("BooksComments")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Book");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.BooksDegerlendirme", b =>
                {
                    b.HasOne("HerkesYazarOlsun.Model.Entity.Books", "Book")
                        .WithMany("BooksDegerlendirme")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Book");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.BooksPages", b =>
                {
                    b.HasOne("HerkesYazarOlsun.Model.Entity.Books", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HerkesYazarOlsun.Model.Entity.Books", null)
                        .WithMany("BooksPageList")
                        .HasForeignKey("BooksID");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.BooksStars", b =>
                {
                    b.HasOne("HerkesYazarOlsun.Model.Entity.Books", "Book")
                        .WithMany("BooksStars")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Book");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.CategoryYayinAyarlari", b =>
                {
                    b.HasOne("HerkesYazarOlsun.Model.Entity.Category", "Category")
                        .WithOne("CategoryYayinAyarlari")
                        .HasForeignKey("HerkesYazarOlsun.Model.Entity.CategoryYayinAyarlari", "CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.FavoriBooks", b =>
                {
                    b.HasOne("HerkesYazarOlsun.Model.Entity.Books", "Book")
                        .WithMany("FavoriBooks")
                        .HasForeignKey("BookId");

                    b.HasOne("HerkesYazarOlsun.Model.Entity.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Profil", b =>
                {
                    b.HasOne("HerkesYazarOlsun.Model.Entity.Users", "User")
                        .WithOne("Profil")
                        .HasForeignKey("HerkesYazarOlsun.Model.Entity.Profil", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.UsersDetails", b =>
                {
                    b.HasOne("HerkesYazarOlsun.Model.Entity.Users", "LoginUser")
                        .WithMany()
                        .HasForeignKey("LoginUserId");

                    b.Navigation("LoginUser");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.WriterFollow", b =>
                {
                    b.HasOne("HerkesYazarOlsun.Model.Entity.Users", "LoginUsers")
                        .WithMany("WriterFollowLoginList")
                        .HasForeignKey("LoginUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HerkesYazarOlsun.Model.Entity.Users", "Yazar")
                        .WithMany("WriterFollowYazarList")
                        .HasForeignKey("YazarId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("LoginUsers");

                    b.Navigation("Yazar");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.WriterStars", b =>
                {
                    b.HasOne("HerkesYazarOlsun.Model.Entity.Users", "LoginUser")
                        .WithMany("WriterStarsLoginList")
                        .HasForeignKey("LoginUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HerkesYazarOlsun.Model.Entity.Users", "Yazar")
                        .WithMany("WriterStarsYazarList")
                        .HasForeignKey("YazarId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("LoginUser");

                    b.Navigation("Yazar");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.YayinAyarlari", b =>
                {
                    b.HasOne("HerkesYazarOlsun.Model.Entity.Books", "Book")
                        .WithOne("YayinAyar")
                        .HasForeignKey("HerkesYazarOlsun.Model.Entity.YayinAyarlari", "BookId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Book");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Books", b =>
                {
                    b.Navigation("BooksComments");

                    b.Navigation("BooksDegerlendirme");

                    b.Navigation("BooksPageList");

                    b.Navigation("BooksStars");

                    b.Navigation("FavoriBooks");

                    b.Navigation("YayinAyar");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Category", b =>
                {
                    b.Navigation("CategoryYayinAyarlari");
                });

            modelBuilder.Entity("HerkesYazarOlsun.Model.Entity.Users", b =>
                {
                    b.Navigation("Profil");

                    b.Navigation("WriterFollowLoginList");

                    b.Navigation("WriterFollowYazarList");

                    b.Navigation("WriterStarsLoginList");

                    b.Navigation("WriterStarsYazarList");
                });
#pragma warning restore 612, 618
        }
    }
}
